import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, AlertTriangle, CheckCircle2, ScanLine, Bot, Download, HardDrive } from 'lucide-react';
import Card, { CardTitle } from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import Badge from '../../components/ui/Badge';
import { mockScans } from '../../data/mockData';
import { formatDate } from '../../utils/formatters';
import type { ScanResult, UploadImageResult } from '../../types';

export default function ScanResultPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  let result: ScanResult | null = null;
  let uploadInfo: UploadImageResult | null = null;
  let imageUrl: string | null = null;
  let scanDate = new Date().toISOString();

  if (id === 'new') {
    // Purge any stale mock diagnoses from sessionStorage
    sessionStorage.removeItem('lastScanResult');

    // Load actual upload metadata
    const storedUpload = sessionStorage.getItem('lastScanUpload');
    const storedImage = sessionStorage.getItem('lastScanImage');

    if (storedUpload) {
      uploadInfo = JSON.parse(storedUpload);
      scanDate = uploadInfo?.uploadedAt || scanDate;
    }
    imageUrl = storedImage;

    // Real uploads strictly have result = null until real backend AI model is connected
    result = null;
  } else {
    // Historical/demo scans by ID (e.g. scan-001 from demo dashboard)
    const scan = mockScans.find((s) => s.id === id);
    if (scan) {
      result = scan.result;
      imageUrl = scan.imageUrl;
      scanDate = scan.scanDate;
    }
  }

  if (!result && !uploadInfo) {
    return (
      <div className="text-center py-16">
        <p className="text-slate-500">Scan result or upload data not found.</p>
        <Button variant="outline" onClick={() => navigate('/app/scan')} className="mt-4">
          Go to Scan Crop
        </Button>
      </div>
    );
  }

  const severityVariant = {
    Low: 'info' as const,
    Moderate: 'warning' as const,
    High: 'danger' as const,
    Severe: 'danger' as const,
  };

  return (
    <div className="space-y-6 max-w-3xl mx-auto">
      <button
        onClick={() => navigate('/app/scan')}
        className="flex items-center gap-2 text-sm text-slate-500 hover:text-slate-700 transition-colors cursor-pointer"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Scan
      </button>

      {/* Real AI Result available (for historical scans or future real AI backend response) */}
      {result ? (
        <>
          {/* AI Disclaimer */}
          <div className="flex items-center gap-2 px-4 py-3 bg-blue-50 border border-blue-200 rounded-xl">
            <Bot className="w-5 h-5 text-blue-600 flex-shrink-0" />
            <p className="text-sm text-blue-700">
              <strong>AI-Assisted Analysis</strong> — This result is generated by AI and should be used as guidance.
              Consult an agricultural expert for critical decisions.
            </p>
          </div>

          {/* Result Card */}
          <Card>
            {/* Image Preview */}
            {imageUrl && imageUrl !== '/placeholder-scan.jpg' && (
              <div className="rounded-xl overflow-hidden mb-6 bg-slate-100">
                <img src={imageUrl} alt="Scanned crop" className="w-full h-48 sm:h-64 object-cover" />
              </div>
            )}

            {/* Status Header */}
            <div className={`p-6 rounded-xl mb-6 ${result.isHealthy ? 'bg-emerald-50 border border-emerald-200' : 'bg-amber-50 border border-amber-200'}`}>
              <div className="flex items-center gap-3 mb-2">
                {result.isHealthy ? (
                  <CheckCircle2 className="w-8 h-8 text-emerald-600" />
                ) : (
                  <AlertTriangle className="w-8 h-8 text-amber-600" />
                )}
                <div>
                  <h2 className="text-xl font-bold text-slate-800">
                    {result.isHealthy ? 'Crop is Healthy' : result.disease}
                  </h2>
                  <p className="text-sm text-slate-500">
                    Scanned on {formatDate(scanDate)}
                  </p>
                </div>
              </div>

              {/* Metrics */}
              <div className="flex items-center gap-4 mt-4">
                <div className="flex items-center gap-2">
                  <span className="text-sm text-slate-600">Confidence:</span>
                  <div className="flex items-center gap-2">
                    <div className="w-24 h-2.5 bg-white rounded-full overflow-hidden">
                      <div
                        className="h-full bg-emerald-500 rounded-full transition-all duration-1000"
                        style={{ width: `${result.confidence}%` }}
                      />
                    </div>
                    <span className="text-sm font-bold text-slate-800">{result.confidence}%</span>
                  </div>
                </div>
                <Badge variant={severityVariant[result.severity]} size="md">
                  {result.severity} Severity
                </Badge>
              </div>
            </div>

            {/* Description */}
            <div className="mb-6">
              <CardTitle>Analysis Details</CardTitle>
              <p className="mt-2 text-sm text-slate-600 leading-relaxed">{result.description}</p>
            </div>

            {/* Recommendations */}
            <div>
              <CardTitle>Recommendations</CardTitle>
              <div className="mt-3 space-y-3">
                {result.recommendations.map((rec, i) => (
                  <div
                    key={i}
                    className="flex items-start gap-3 p-3 bg-slate-50 rounded-xl"
                  >
                    <span className="w-6 h-6 rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center text-xs font-bold flex-shrink-0">
                      {i + 1}
                    </span>
                    <span className="text-sm text-slate-600">{rec}</span>
                  </div>
                ))}
              </div>
            </div>
          </Card>
        </>
      ) : uploadInfo ? (
        /* Real Upload State: Verified S3 upload without fake diagnoses */
        <>
          <div className="flex items-center gap-3 px-4 py-3 bg-blue-50 border border-blue-200 rounded-xl">
            <Bot className="w-5 h-5 text-blue-600 flex-shrink-0" />
            <p className="text-sm text-blue-800">
              <strong>AWS S3 Upload Verified</strong> — Crop image uploaded successfully. AI disease analysis is not connected yet.
            </p>
          </div>

          <Card>
            {/* Image Preview */}
            {imageUrl && (
              <div className="rounded-xl overflow-hidden mb-6 bg-slate-100">
                <img src={imageUrl} alt="Uploaded crop" className="w-full h-48 sm:h-64 object-cover" />
              </div>
            )}

            {/* Status Header */}
            <div className="p-6 rounded-xl mb-6 bg-emerald-50 border border-emerald-200">
              <div className="flex items-center gap-3 mb-2">
                <CheckCircle2 className="w-8 h-8 text-emerald-600" />
                <div>
                  <h2 className="text-xl font-bold text-slate-800">
                    Crop Image Uploaded Successfully
                  </h2>
                  <p className="text-sm text-slate-500">
                    Uploaded on {formatDate(scanDate)}
                  </p>
                </div>
              </div>
              <p className="mt-2 text-xs text-emerald-800 font-mono bg-white/70 px-3 py-1.5 rounded-lg border border-emerald-100 inline-block break-all">
                S3 Key: {uploadInfo.key}
              </p>
            </div>

            {/* Storage Details */}
            <div className="mb-6">
              <CardTitle>Storage Details</CardTitle>
              <div className="mt-3 grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
                <div className="p-3 bg-slate-50 rounded-xl flex items-center gap-2.5">
                  <HardDrive className="w-4 h-4 text-slate-400 shrink-0" />
                  <div className="truncate">
                    <span className="text-slate-400 text-xs block">File Name</span>
                    <span className="font-medium text-slate-700 truncate">{uploadInfo.fileName}</span>
                  </div>
                </div>
                <div className="p-3 bg-slate-50 rounded-xl">
                  <span className="text-slate-400 text-xs block">File Size</span>
                  <span className="font-medium text-slate-700">
                    {(uploadInfo.fileSize / 1024 / 1024).toFixed(2)} MB
                  </span>
                </div>
                <div className="p-3 bg-slate-50 rounded-xl">
                  <span className="text-slate-400 text-xs block">Content Type</span>
                  <span className="font-medium text-slate-700">{uploadInfo.contentType}</span>
                </div>
                <div className="p-3 bg-slate-50 rounded-xl">
                  <span className="text-slate-400 text-xs block">Storage Destination</span>
                  <span className="font-medium text-slate-700">AWS S3 (eu-north-1)</span>
                </div>
              </div>
            </div>

            {/* AI Analysis Status */}
            <div>
              <CardTitle>AI Disease Analysis</CardTitle>
              <div className="mt-3 p-4 bg-slate-50 border border-slate-200 rounded-xl space-y-1.5 text-sm text-slate-600">
                <div className="flex items-center gap-2 text-slate-700 font-semibold">
                  <span className="w-2 h-2 rounded-full bg-amber-500 animate-pulse" />
                  Pipeline Status: Pending Integration
                </div>
                <p className="text-xs text-slate-500 leading-relaxed pt-1">
                  AI disease analysis is not connected yet. Your crop image is securely saved in Amazon S3. Real-time diagnosis and recommendations will be populated here once the backend AI model pipeline is activated.
                </p>
              </div>
            </div>
          </Card>
        </>
      ) : null}

      {/* Actions */}
      <div className="flex flex-col sm:flex-row gap-3">
        <Button
          className="flex-1"
          onClick={() => navigate('/app/scan')}
          icon={<ScanLine className="w-4 h-4" />}
        >
          Scan Another Crop
        </Button>
        <Button variant="outline" className="flex-1" icon={<Download className="w-4 h-4" />}>
          Save Report
        </Button>
      </div>
    </div>
  );
}
