import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, AlertTriangle, CheckCircle2, ScanLine, Bot, Download } from 'lucide-react';
import Card, { CardTitle } from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import Badge from '../../components/ui/Badge';
import { mockScans } from '../../data/mockData';
import { formatDate } from '../../utils/formatters';
import type { ScanResult } from '../../types';

export default function ScanResultPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  let result: ScanResult | null = null;
  let imageUrl: string | null = null;
  let scanDate = new Date().toISOString();

  if (id === 'new') {
    // Load from sessionStorage (from ScanCropPage)
    const stored = sessionStorage.getItem('lastScanResult');
    const storedImage = sessionStorage.getItem('lastScanImage');
    if (stored) {
      result = JSON.parse(stored);
      imageUrl = storedImage;
    }
  } else {
    const scan = mockScans.find((s) => s.id === id);
    if (scan) {
      result = scan.result;
      imageUrl = scan.imageUrl;
      scanDate = scan.scanDate;
    }
  }

  if (!result) {
    return (
      <div className="text-center py-16">
        <p className="text-slate-500">Scan result not found.</p>
        <Button variant="outline" onClick={() => navigate('/app/scan')} className="mt-4">
          Go to Scan
        </Button>
      </div>
    );
  }

  const severityVariant = {
    Low: 'info' as const,
    Moderate: 'warning' as const,
    High: 'danger' as const,
    Severe: 'danger' as const,
  };

  return (
    <div className="space-y-6 max-w-3xl mx-auto">
      <button
        onClick={() => navigate('/app/scan')}
        className="flex items-center gap-2 text-sm text-slate-500 hover:text-slate-700 transition-colors cursor-pointer"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Scan
      </button>

      {/* AI Disclaimer */}
      <div className="flex items-center gap-2 px-4 py-3 bg-blue-50 border border-blue-200 rounded-xl">
        <Bot className="w-5 h-5 text-blue-600 flex-shrink-0" />
        <p className="text-sm text-blue-700">
          <strong>AI-Assisted Analysis</strong> — This result is generated by AI and should be used as guidance.
          Consult an agricultural expert for critical decisions.
        </p>
      </div>

      {/* Result Card */}
      <Card>
        {/* Image Preview */}
        {imageUrl && imageUrl !== '/placeholder-scan.jpg' && (
          <div className="rounded-xl overflow-hidden mb-6 bg-slate-100">
            <img src={imageUrl} alt="Scanned crop" className="w-full h-48 sm:h-64 object-cover" />
          </div>
        )}

        {/* Status Header */}
        <div className={`p-6 rounded-xl mb-6 ${result.isHealthy ? 'bg-emerald-50 border border-emerald-200' : 'bg-amber-50 border border-amber-200'}`}>
          <div className="flex items-center gap-3 mb-2">
            {result.isHealthy ? (
              <CheckCircle2 className="w-8 h-8 text-emerald-600" />
            ) : (
              <AlertTriangle className="w-8 h-8 text-amber-600" />
            )}
            <div>
              <h2 className="text-xl font-bold text-slate-800">
                {result.isHealthy ? 'Crop is Healthy' : result.disease}
              </h2>
              <p className="text-sm text-slate-500">
                Scanned on {formatDate(scanDate)}
              </p>
            </div>
          </div>

          {/* Metrics */}
          <div className="flex items-center gap-4 mt-4">
            <div className="flex items-center gap-2">
              <span className="text-sm text-slate-600">Confidence:</span>
              <div className="flex items-center gap-2">
                <div className="w-24 h-2.5 bg-white rounded-full overflow-hidden">
                  <div
                    className="h-full bg-emerald-500 rounded-full transition-all duration-1000"
                    style={{ width: `${result.confidence}%` }}
                  />
                </div>
                <span className="text-sm font-bold text-slate-800">{result.confidence}%</span>
              </div>
            </div>
            <Badge variant={severityVariant[result.severity]} size="md">
              {result.severity} Severity
            </Badge>
          </div>
        </div>

        {/* Description */}
        <div className="mb-6">
          <CardTitle>Analysis Details</CardTitle>
          <p className="mt-2 text-sm text-slate-600 leading-relaxed">{result.description}</p>
        </div>

        {/* Recommendations */}
        <div>
          <CardTitle>Recommendations</CardTitle>
          <div className="mt-3 space-y-3">
            {result.recommendations.map((rec, i) => (
              <div
                key={i}
                className="flex items-start gap-3 p-3 bg-slate-50 rounded-xl"
              >
                <span className="w-6 h-6 rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center text-xs font-bold flex-shrink-0">
                  {i + 1}
                </span>
                <span className="text-sm text-slate-600">{rec}</span>
              </div>
            ))}
          </div>
        </div>
      </Card>

      {/* Actions */}
      <div className="flex flex-col sm:flex-row gap-3">
        <Button
          className="flex-1"
          onClick={() => navigate('/app/scan')}
          icon={<ScanLine className="w-4 h-4" />}
        >
          Scan Another Crop
        </Button>
        <Button variant="outline" className="flex-1" icon={<Download className="w-4 h-4" />}>
          Save Report
        </Button>
      </div>
    </div>
  );
}
